name: balance-index-2.0
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.9

  # Core scientific computing
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0

  # Statistical analysis
  - statsmodels>=0.12.0
  - seaborn>=0.11.0

  # Visualization
  - matplotlib>=3.4.0
  - plotly>=5.0.0
  - bokeh>=2.4.0

  # Geospatial analysis
  - geopandas>=0.9.0
  - folium>=0.12.0

  # Data processing
  - openpyxl>=3.0.0
  - xlsxwriter>=3.0.0
  - requests>=2.26.0
  - lxml>=4.6.0

  # Jupyter ecosystem
  - jupyter>=1.0.0
  - jupyterlab>=3.2.0
  - ipykernel>=6.4.0

  # Machine learning
  - xgboost>=1.5.0
  - lightgbm>=3.3.0

  # Database and configuration
  - sqlalchemy>=1.4.0
  - python-dotenv>=0.19.0
  - pyyaml>=6.0

  # Progress tracking
  - tqdm>=4.62.0

  # Development tools
  - pytest>=6.2.0

  # Pip dependencies
  - pip
  - pip:
    - pingouin>=0.5.0
    - catboost>=1.0.0

# Environment for Balance Index 2.0 research
# 22-day comprehensive analysis across 133 countries
# 
# To create environment:
# conda env create -f environment.yml
# conda activate balance-index-2.0
#
# Research findings:
# - 635,316 adult graduates analyzed
# - Balance Index vs Employment: r = -0.72*** (p < 0.001)
# - Data sources: UNESCO, OECD, World Bank, ILO, Oxford, IMF, WIPO, BLS
