name: BI compute (manual)

on:
  # 수동 실행 + 실행할 Git ref 입력받기
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref to checkout (branch/tag/SHA)"
        required: true
        default: "hssc-2025-sync"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 여기서 입력한 ref(예: hssc-2025-sync)를 체크아웃
      - name: Checkout target ref
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install -r code/env/requirements.txt

      - name: Patch tokens (optional)
        run: |
          if [ -f docs/_autofill.yml ]; then python code/patch_tokens.py || true; fi

      - name: Run BI pipeline
        run: |
          python code/01_build_balance_index.py
          python code/02_oecd_validation.py

      - name: Install pandoc & TeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Export manuscript
        run: bash .ci/export.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bi-results
          path: |
            data/processed/**
            tables/**
            docs/manuscript.pdf
            docs/manuscript.docx
