name: BI compute (auto-commit)
# trigger
on:
  # 이 워크플로우 파일을 수정해서 커밋하면 자동 실행됩니다.
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/bi_compute.yml"
  # 원하면 버튼으로도 실행 가능
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 분석할 코드는 hssc-2025-sync 브랜치에서 가져옵니다.
      - name: Checkout target code (hssc-2025-sync)
        uses: actions/checkout@v4
        with:
          ref: hssc-2025-sync
          persist-credentials: true

      - name: Verify inputs
        run: |
          set -e
          test -f data/raw/UNESCO_UIS.csv || (echo "::error::missing data/raw/UNESCO_UIS.csv"; exit 1)
          test -f data/raw/OECD_EAG_2024.csv  || (echo "::error::missing data/raw/OECD_EAG_2024.csv"; exit 1)

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps (robust)
        run: |
          python -m pip install -U pip
          if [ -f code/env/requirements.txt ]; then
            python -m pip install -r code/env/requirements.txt
          elif [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          else
            echo "pandas>=2.2
numpy>=1.26
scipy>=1.11
statsmodels>=0.14
matplotlib>=3.8
pyreadstat
pyyaml" > /tmp/reqs.txt
            python -m pip install -r /tmp/reqs.txt
          fi

      - name: Run BI pipeline
        run: |
          set -e
          python code/01_build_balance_index.py
          python code/02_oecd_validation.py
          ls -lah data/processed || true
          ls -lah tables || true

      # ★ 결과를 hssc-2025-sync 브랜치에 커밋/푸시
      - name: Commit results back to hssc-2025-sync
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A data/processed tables || true
          git commit -m "ci: BI outputs from workflow run" || echo "No changes to commit"
          git push origin HEAD:hssc-2025-sync
