name: BI compute (manual)

on:
  workflow_dispatch: {}   # 버튼 눌러서 수동 실행

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install -r code/env/requirements.txt

      - name: Run BI pipeline
        run: |
          python code/01_build_balance_index.py
          python code/02_oecd_validation.py
        env:
          PYTHONUTF8: 1

      - name: Show outputs
        run: |
          ls -lah data/processed || true
          ls -lah tables || true

      - name: Upload artifacts (results)
        uses: actions/upload-artifact@v4
        with:
          name: bi-results
          path: |
            data/processed/**
            tables/**
